//! flsnd — AUR-1 sound bank tool (Block 16, tasks 16.1 and 16.5).
//!
//! Usage:
//!   flsnd notes <out.inc>          emit the note table as flas source
//!   flsnd dump  <bank.flsnd>       human-readable bank listing
//!
//! SILENT ON SUCCESS, like flas, fll, and fldisk — a Zig build step that
//! declares an output file captures the child's streams and fails on
//! unexpected stderr, and `notes` is generated exactly that way. `dump`
//! prints because printing is the whole point of it.
//!
//! `notes` is the one encoder of pitch, in the sense encode.zig is the one
//! encoder of instructions (audit P1). VFREQ is a phase increment, not a
//! frequency — reg = round(Hz × 65536 / rate) — so a hand-written table
//! would be a second implementation of that formula, free to drift. The
//! table is generated, and the tests below pin it against the same
//! arithmetic the Phase 4 register test used: A4 = $028E.

const std = @import("std");

/// Internal synthesis rate at ASRATE 0 (v1.1 §6.2). The table is
/// rate-specific: ASRATE 1 or 2 halves or quarters every pitch, which is
/// why sndlib locks the rate rather than rescaling at runtime.
pub const rate_hz: f64 = 44100.0;

/// C0 … B7 — eight octaves, MIDI-style with note 57 = A4 = 440 Hz.
pub const note_count: u32 = 96;
pub const a4_index: u32 = 57;

pub fn noteHz(index: u32) f64 {
    return 440.0 * std.math.pow(f64, 2.0, (@as(f64, @floatFromInt(index)) -
        @as(f64, @floatFromInt(a4_index))) / 12.0);
}

/// The phase increment the AUR-1 wants for `index` (v1.1 §6.2).
pub fn noteReg(index: u32) u16 {
    return @intFromFloat(@round(noteHz(index) * 65536.0 / rate_hz));
}

/// What that increment actually sounds, and how far off it is in cents.
fn actualHz(reg: u16) f64 {
    return @as(f64, @floatFromInt(reg)) * rate_hz / 65536.0;
}

fn centsError(index: u32) f64 {
    const r = noteReg(index);
    if (r == 0) return 0;
    return 1200.0 * std.math.log2(actualHz(r) / noteHz(index));
}

const note_names = [12][]const u8{ "C ", "C#", "D ", "D#", "E ", "F ", "F#", "G ", "G#", "A ", "A#", "B " };

fn writeNoteTable(w: *std.Io.Writer) !void {
    try w.print(
        \\; ============================================================================
        \\; notes.inc — VFREQ phase increments for C0..B7 at ASRATE 0 (44.1 kHz).
        \\;
        \\; GENERATED by `flsnd notes` — do not edit. The formula is
        \\; reg = round(Hz * 65536 / 44100), so this table is valid ONLY at
        \\; ASRATE 0; rates 1 and 2 transpose everything down an octave or two.
        \\;
        \\; Resolution is the thing to watch in the bottom octave. One LSB spans
        \\; {d:.0} cents at C0 against {d:.1} cents at A4, so the low notes are
        \\; coarse: worst tuning error over the whole table is {d:.1} cents, all of
        \\; it below C2. From C2 up every note is within 4 cents, which is
        \\; inaudible. C0-C1 are usable for bass but audibly tempered.
        \\; ============================================================================
        \\
        \\note_table:
        \\
    , .{ centsPerLsb(0), centsPerLsb(a4_index), worstCents() });

    var octave: u32 = 0;
    while (octave < note_count / 12) : (octave += 1) {
        try w.print("    ; octave {d}\n", .{octave});
        var n: u32 = 0;
        while (n < 12) : (n += 1) {
            const i = octave * 12 + n;
            const r = noteReg(i);
            // Zig's format spec has no '+' sign flag — after ':' it wants
            // [fill][alignment][width].[precision] — so the sign is written
            // by hand rather than borrowed from printf.
            const err = centsError(i);
            try w.print("    DW ${X:0>4}    ; {s}{d}  {d:>7.2} Hz -> {d:>7.2} Hz  {s}{d:>4.1} cents\n", .{
                r,
                note_names[n],
                octave,
                noteHz(i),
                actualHz(r),
                if (err < 0) "-" else "+",
                @abs(err),
            });
        }
    }
    try w.print("\n    EQU NOTE_COUNT, {d}\n    EQU NOTE_A4, {d}\n", .{ note_count, a4_index });
}

fn centsPerLsb(index: u32) f64 {
    const r = noteReg(index);
    if (r == 0) return 0;
    return 1200.0 * std.math.log2(@as(f64, @floatFromInt(r + 1)) / @as(f64, @floatFromInt(r)));
}

fn worstCents() f64 {
    var worst: f64 = 0;
    var i: u32 = 0;
    while (i < note_count) : (i += 1) {
        const c = @abs(centsError(i));
        if (c > worst) worst = c;
    }
    return worst;
}

// ---------------------------------------------------------------------------
// .flsnd bank format (amendment v1.3 §5).
// ---------------------------------------------------------------------------

pub const patch_size: u32 = 128;
pub const wavetable_size: u32 = 256;
pub const modtable_size: u32 = 32;
pub const header_size: u32 = 16;
pub const max_patches: u32 = 32;

/// Patch field offsets. The first 80 bytes are a byte image of the chip's
/// $80100-$8014F, which is what makes snd_load_patch a block copy.
pub const p_voices: u32 = 0x00; // 4 x 16-byte voice blocks
pub const p_global: u32 = 0x40;
pub const p_name: u32 = 0x50; // 16 ASCII bytes
pub const p_mod: u32 = 0x60; // 4 x 8-byte descriptors

/// Global-block offsets that are NOT a straight chip image (v1.3 §5.2).
pub const g_arch: u32 = 0x0B; // repurposed ASTAT — write-1-to-clear, never loaded
pub const g_transpose: u32 = 0x0C;
pub const g_tickdiv: u32 = 0x0D;

pub const Error = error{ NotFlsnd, BadVersion, BadImage, TooManyPatches };

pub const Bank = struct {
    bytes: []const u8,

    pub fn check(b: Bank) Error!void {
        if (b.bytes.len < header_size) return Error.BadImage;
        if (b.bytes[0] != 'F' or b.bytes[1] != 'S') return Error.NotFlsnd;
        if (std.mem.readInt(u16, b.bytes[2..4], .little) != 1) return Error.BadVersion;
        if (b.patchCount() > max_patches) return Error.TooManyPatches;
        if (b.bytes.len < b.expectedLen()) return Error.BadImage;
    }

    pub fn patchCount(b: Bank) u32 {
        return b.bytes[4];
    }
    pub fn wavetableCount(b: Bank) u32 {
        return b.bytes[5];
    }
    pub fn modtableCount(b: Bank) u32 {
        return b.bytes[6];
    }

    pub fn expectedLen(b: Bank) u32 {
        return header_size + b.patchCount() * patch_size +
            b.wavetableCount() * wavetable_size + b.modtableCount() * modtable_size;
    }

    pub fn patch(b: Bank, index: u32) []const u8 {
        return b.bytes[header_size + index * patch_size ..][0..patch_size];
    }

    /// Trailing spaces trimmed — names are stored space-padded to 16.
    pub fn patchName(b: Bank, index: u32) []const u8 {
        const raw = b.patch(index)[p_name..][0..16];
        var end: usize = raw.len;
        while (end > 0 and raw[end - 1] == ' ') end -= 1;
        return raw[0..end];
    }
};

const arch_names = [3][]const u8{ "4x mono", "FM 0+1, mono 2,3", "2x FM pair" };
const wave_names = [8][]const u8{ "sine", "square", "triangle", "saw", "pulse", "noise", "wavetable", "reserved" };

fn dumpBank(b: Bank, w: *std.Io.Writer) !void {
    try w.print("bank: {d} patch(es), {d} wavetable(s), {d} mod table(s), {d} bytes\n", .{
        b.patchCount(), b.wavetableCount(), b.modtableCount(), b.bytes.len,
    });
    var i: u32 = 0;
    while (i < b.patchCount()) : (i += 1) {
        const p = b.patch(i);
        const arch = p[p_global + g_arch];
        try w.print("\n{d:>2}  \"{s}\"\n    arch {d} ({s})  transpose {d}  tick/{d}\n", .{
            i,
            b.patchName(i),
            arch,
            if (arch < 3) arch_names[arch] else "invalid",
            @as(i8, @bitCast(p[p_global + g_transpose])),
            p[p_global + g_tickdiv],
        });
        var v: u32 = 0;
        while (v < 4) : (v += 1) {
            const vb = p[p_voices + v * 16 ..][0..16];
            const wave = vb[2] & 0x07;
            const fm = (vb[2] & 0x08) != 0;
            try w.print("    voice {d}: {s:<10} vol ${X:0>2}  ADSR ${X:0>2}/${X:0>2}  pan {d}/{d}{s}{s}{s}\n", .{
                v,
                wave_names[wave],
                vb[7],
                vb[4],
                vb[5],
                vb[14] & 0x0F,
                vb[13] & 0x0F,
                if (fm and v % 2 == 0) "  FM modulator" else "",
                if (vb[3] & 0x40 != 0) "  ring" else "",
                if (vb[3] & 0x20 != 0) "  sync" else "",
            });
        }
    }
}

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);

    if (args.len < 3) {
        std.debug.print(
            \\usage:
            \\  flsnd notes <out.inc>
            \\  flsnd dump  <bank.flsnd>
            \\
        , .{});
        return error.BadUsage;
    }
    const verb = args[1];
    const path = args[2];
    const cwd = std.Io.Dir.cwd();

    if (std.mem.eql(u8, verb, "notes")) {
        var file = try cwd.createFile(io, path, .{});
        defer file.close(io);
        var buf: [8192]u8 = undefined;
        var fw = file.writer(io, &buf);
        try writeNoteTable(&fw.interface);
        try fw.interface.flush();
        return;
    }

    if (std.mem.eql(u8, verb, "dump")) {
        const bytes = try cwd.readFileAlloc(io, path, arena, .limited(1 << 20));
        const bank = Bank{ .bytes = bytes };
        try bank.check();
        var buf: [4096]u8 = undefined;
        var sw = std.Io.File.stdout().writer(io, &buf);
        try dumpBank(bank, &sw.interface);
        try sw.interface.flush();
        return;
    }

    std.debug.print("flsnd: unknown command {s}\n", .{verb});
    return error.BadUsage;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

test "flsnd: A4 is $028E, the value the Phase 4 register test uses" {
    try testing.expectEqual(@as(u16, 0x028E), noteReg(a4_index));
    try testing.expectEqual(@as(u16, 654), noteReg(a4_index));
    // …and the octaves either side are exact doublings of it, give or take
    // one LSB of rounding.
    try testing.expectEqual(@as(u16, 327), noteReg(a4_index - 12));
    try testing.expectEqual(@as(u16, 1308), noteReg(a4_index + 12));
}

test "flsnd: the table is monotonic and spans the audible range" {
    var prev: u16 = 0;
    var i: u32 = 0;
    while (i < note_count) : (i += 1) {
        const r = noteReg(i);
        try testing.expect(r > prev); // strictly rising: no two notes collide
        prev = r;
    }
    try testing.expectEqual(@as(u16, 24), noteReg(0)); // C0 ~16.35 Hz
    try testing.expectEqual(@as(u16, 5872), noteReg(95)); // B7 ~3951 Hz
    // Nyquist at rate 0 is $8000; the top note must sit far below it.
    try testing.expect(noteReg(95) < 0x8000 / 4);
}

test "flsnd: tuning error is bounded, and concentrated in the bottom octaves" {
    // The whole table is within a quarter tone…
    try testing.expect(worstCents() < 25.0);
    // …but that error lives at the bottom: from C2 up nothing exceeds
    // 4 cents, which is inaudible.
    var i: u32 = 24; // C2
    while (i < note_count) : (i += 1) {
        try testing.expect(@abs(centsError(i)) < 4.0);
    }
    // C0 is the coarse one: one LSB there spans most of a semitone, which
    // is why sndlib documents C0-C1 as tempered rather than accurate.
    try testing.expect(centsPerLsb(0) > 60.0);
    try testing.expect(centsPerLsb(a4_index) < 3.0);
}

test "flsnd: generated source carries the table and its own provenance" {
    var buf: [64 * 1024]u8 = undefined;
    var w = std.Io.Writer.fixed(&buf);
    try writeNoteTable(&w);
    const out = w.buffered();
    try testing.expect(std.mem.indexOf(u8, out, "GENERATED by `flsnd notes`") != null);
    try testing.expect(std.mem.indexOf(u8, out, "note_table:") != null);
    try testing.expect(std.mem.indexOf(u8, out, "DW $028E") != null); // A4
    try testing.expect(std.mem.indexOf(u8, out, "EQU NOTE_A4, 57") != null);
    // One DW per note, no more.
    var count: u32 = 0;
    var it = std.mem.splitScalar(u8, out, '\n');
    while (it.next()) |line| {
        if (std.mem.startsWith(u8, line, "    DW ")) count += 1;
    }
    try testing.expectEqual(note_count, count);
}

test "flsnd: bank validation rejects what it should" {
    var img: [header_size + patch_size]u8 = @splat(0);
    img[0] = 'F';
    img[1] = 'S';
    std.mem.writeInt(u16, img[2..4], 1, .little);
    img[4] = 1; // one patch
    try (Bank{ .bytes = &img }).check();

    var bad = img;
    bad[1] = 'X';
    try testing.expectError(Error.NotFlsnd, (Bank{ .bytes = &bad }).check());

    var wrong_ver = img;
    std.mem.writeInt(u16, wrong_ver[2..4], 2, .little);
    try testing.expectError(Error.BadVersion, (Bank{ .bytes = &wrong_ver }).check());

    var too_many = img;
    too_many[4] = 33;
    try testing.expectError(Error.TooManyPatches, (Bank{ .bytes = &too_many }).check());

    // Truncated: the header claims a patch the file does not contain.
    try testing.expectError(Error.BadImage, (Bank{ .bytes = img[0..header_size] }).check());
}

test "flsnd: patch names are space-padded on disk, trimmed on the way out" {
    var img: [header_size + patch_size]u8 = @splat(0);
    img[0] = 'F';
    img[1] = 'S';
    std.mem.writeInt(u16, img[2..4], 1, .little);
    img[4] = 1;
    const name_at = header_size + p_name;
    @memset(img[name_at..][0..16], ' ');
    @memcpy(img[name_at..][0..4], "BASS");
    const bank = Bank{ .bytes = &img };
    try bank.check();
    try testing.expectEqualStrings("BASS", bank.patchName(0));
    // An all-space name trims to empty rather than underflowing.
    @memset(img[name_at..][0..16], ' ');
    try testing.expectEqualStrings("", bank.patchName(0));
}
